### ISSUE TITLE
GlobalKTable backed by RocksDB: Unable to write a negative offset to the checkpoint file

### ISSUE THREAD

**Issue by hedmavx** [LGouellec/streamiz#387]
# Description

We are trying to create a GlobalKTable backed by RocksDB and encounter the following errors:

```
[13:20:31:333 WRN] Fabians-MBP 24 Failed to write offset checkpoint for global stores: Unable to write a negative offset to the checkpoint file <s:Streamiz.Kafka.Net.Processors.Internal.GlobalStateManager>
[13:20:31:441 DBG] Fabians-MBP 24 Flushing all global globalStores registered in the state manager <s:Streamiz.Kafka.Net.Processors.Internal.GlobalStateManager>
[13:20:31:441 DBG] Fabians-MBP 24 Flushing store brokerage-trade-transactions-command-validation-accounts-by-ref-global-ktable <s:Streamiz.Kafka.Net.Processors.Internal.GlobalStateManager>
[13:20:31:441 ERR] Fabians-MBP 24 Received offset -2 to write to checkpoint file for topic:trex-simonier-x-3-accounts-by-ref|partition:[0] <s:Streamiz.Kafka.Net.State.OffsetCheckpointFile>
[13:20:31:442 WRN] Fabians-MBP 24 Failed to write offset checkpoint for global stores: Unable to write a negative offset to the checkpoint file <s:Streamiz.Kafka.Net.Processors.Internal.GlobalStateManager>
```
When changing to InMemory everything works fine, this is the current workaround which we are using.
OS: MacOS 15.1
Affected Streamiz Versions: 1.6,1.5
# How to reproduce

### config
```fsharp
StreamConfig<StringSerDes, StringSerDes>(
ApplicationId = config.ServiceConfig.ServiceName,
BootstrapServers = config.Kafka.BootstrapServers,
AutoRegisterSchemas = true,
SchemaRegistryUrl = config.Kafka.SchemaRegistry.ToString(),
NumStreamThreads = 8,
ReplicationFactor = 1,
AutoOffsetReset = AutoOffsetReset.Earliest,
Guarantee = ProcessingGuarantee.EXACTLY_ONCE,
CommitIntervalMs = 100,
LingerMs = 0,
PollMs = 10,
MaxPollIntervalMs = 10000,
SessionTimeoutMs = 10000,
CompressionType = CompressionType.Zstd,
Logger = loggerFactory,
MetricsRecording = MetricsRecordingLevel.DEBUG,
InnerExceptionHandler = (fun _ -> ExceptionHandlerResponse.FAIL), 
ProductionExceptionHandler = (fun _ -> ProductionExceptionHandlerResponse.FAIL),
DeserializationExceptionHandler = (fun _ _ _ -> ExceptionHandlerResponse.FAIL)
    )
```
### topology
```fsharp
        let streamBuilder = StreamBuilder()

        streamBuilder.GlobalTable(
                "some-topic",
                StringSerDes(),
                StringSerDes(),
                RocksDb.As<
                    string,
                    string,
                    StringSerDes,
                    StringSerDes
                 >("some-global-ktable")
                ) 

```
## docker

```yaml
services:
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    hostname: kafka
    container_name: kafka
    ports:
      - 29092:29092
      - 29997:9997
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_NUM_PARTITIONS: 8
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997

  karapace-registry:
    image: ghcr.io/aiven-open/karapace:4.0.0
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      KARAPACE_ADVERTISED_HOSTNAME: karapace-registry
      KARAPACE_BOOTSTRAP_URI: kafka:9092
      KARAPACE_PORT: 8081
      KARAPACE_HOST: 0.0.0.0
      KARAPACE_CLIENT_ID: karapace
      KARAPACE_GROUP_ID: karapace-registry
      KARAPACE_MASTER_ELIGIBILITY: "true"
      KARAPACE_TOPIC_NAME: _schemas
      KARAPACE_LOG_LEVEL: WARNING
      KARAPACE_COMPATIBILITY: FULL
      KARAPACE_KAFKA_SCHEMA_READER_STRICT_MODE: false
      KARAPACE_KAFKA_RETRIABLE_ERRORS_SILENCED: true

  karapace-rest:
    image: ghcr.io/aiven-open/karapace:4.0.0
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - rest
    depends_on:
      - kafka
      - karapace-registry
    ports:
      - "8082:8082"
    environment:
      KARAPACE_PORT: 8082
      KARAPACE_HOST: 0.0.0.0
      KARAPACE_ADVERTISED_HOSTNAME: karapace-rest
      KARAPACE_BOOTSTRAP_URI: kafka:9092
      KARAPACE_REGISTRY_HOST: karapace-registry
      KARAPACE_REGISTRY_PORT: 8081
      KARAPACE_ADMIN_METADATA_MAX_AGE: 0
      KARAPACE_LOG_LEVEL: WARNING
      KARAPACE_KAFKA_SCHEMA_READER_STRICT_MODE: false
      KARAPACE_KAFKA_RETRIABLE_ERRORS_SILENCED: true

  kafdrop:
    platform: linux/amd64
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      SCHEMAREGISTRY_CONNECT: "http://localhost:8081"
      CMD_ARGS: "--message.format=PROTOBUF"
    depends_on:
      - kafka
      - karapace-registry

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8888:8080
    depends_on:
      - kafka
      - karapace-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://karapace-registry:8081
      # KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      # KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083
      DYNAMIC_CONFIG_ENABLED: 'true'  # not necessary, added for tests
      KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: 'true'
      KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED: 'true'
```

Checklist
=========

Please provide the following information:
- [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
- [x] A code snippet with your topology builder (ex: builder.Stream<string, string>("topic").to("an-another-topic");)
- [x] Streamiz.Kafka.Net nuget version.
- [x] Apache Kafka version.
- [x] Client configuration.
- [x] Operating system.
- [x] Provide logs (with in debug mode (log4net and StreamConfig.Debug) as necessary in configuration).
- [x] Critical issue.
